### ISSUE TITLE
Pod Security Admissionを追加する

### ISSUE THREAD

**Issue by mktkhr** [mktkhr/stamp-iot#160]
## 目的

- podの特権実行に制限をかける
  - https://kubernetes.io/ja/docs/concepts/security/pod-security-admission/

## 期待結果

- ユーザーのrootに昇格等，セキュリティ的に問題がある挙動を制限していること

**Comment by mktkhr** [comment]
PSAはnamespaceに対して適用する
既存のnamespaceは手動で作成していたので，明示的にmanifestで定義した方がいい

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: hogehoge-ns
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted

```
